name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: clone lib
      run: git submodule update --init --recursive
    - name:
        apt-get -yq python3 python3-dev python3-pip
    - name: Install dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install pytest
    - name: make
      run: make
    - name: make check
      run: make check
